<?xml version="1.0" encoding="utf-8"?><Database Name="SqlUserDatabase" Class="UserDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\SqlUserDatabase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="LoginPanelApplication.Properties.Settings" SettingsPropertyName="SqlUserDatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Login" Member="LoginDatas">
    <Type Name="LoginData">
      <Column Name="LoginId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_LoginData" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChangePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateOfEmployment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[In]" Member="In" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Out" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_LoginData" Member="LoginDatas" ThisKey="UserID" OtherKey="UserID" Type="LoginData" />
      <Association Name="User_Loginfo" Member="Loginfos" ThisKey="UserID" OtherKey="UserID" Type="Loginfo" />
    </Type>
  </Table>
  <Table Name="dbo.Loginfo" Member="Loginfos">
    <Type Name="Loginfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LogoutDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Loginfo" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>